CREATE DATABASE GestaoEstoque;

USE GestaoEstoque;

CREATE TABLE estoque (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
codigo VARCHAR(50) NOT NULL,
descricao TEXT NOT NULL,
localizacao VARCHAR(20) NOT NULL,
qtd_base INT NOT NULL,
qtd_saida INT NOT NULL,
qtd_entrada INT NOT NULL,
qtd_final INT NOT NULL,
estoque_critico VARCHAR(100) NOT NULL
);

CREATE TABLE saida (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
codigo VARCHAR(50) NOT NULL,
matricula VARCHAR(50) NOT NULL,
descricao TEXT NOT NULL,
destino VARCHAR(20) NOT NULL,
qtd_saida INT NOT NULL,
data_saida DATETIME NOT NULL
);

CREATE TABLE entrada (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
codigo VARCHAR(50) NOT NULL,
matricula VARCHAR(50) NOT NULL,
descricao TEXT NOT NULL,
destino VARCHAR(20) NOT NULL,
qtd_saida INT NOT NULL,
data_entrada DATETIME NOT NULL
);

CREATE TABLE armario_fogo (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
codigo VARCHAR(50) NOT NULL,
descricao TEXT NOT NULL,
fispq TEXT NOT NULL,
quantidade INT NOT NULL,
nivel SMALLINT NOT NULL
);

CREATE TABLE produtos (
id INT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
codigo VARCHAR(50) NOT NULL,
cen VARCHAR(10) NOT NULL,
descricao TEXT NOT NULL,
quantidade INT NOT NULL
);